Repository finance-quote/finance-quote, pull requests merged in 2020-10, with the labels that each got.

#149 FQ API improvements - Merge new-new branch into master
  .gitignore
  Documentation/Hackers-Guide
  lib/Finance/Quote.pm
  lib/Finance/Quote/IEXCloud.pm
  new-API-notes.txt
  t/fq-class-methods.t
  t/fq-object-methods.t
  t/iexcloud.t
Labels: next release

#151 Fetching quotes from XETRA (Frankfurt stock exchange)
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/XETRA.pm
  t/xetra.t
Labels: next release

#144 India stocks: quotes from NSE and BSE
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/BSEIndia.pm
  lib/Finance/Quote/NSEIndia.pm
  t/bseindia.t
  t/nseindia.t
Labels: new module, next release

#143 Indiamutual: reduce memory usage.
  lib/Finance/Quote/IndiaMutual.pm
Labels: enhancement, next release

#59 Update URL to SEB funds
  lib/Finance/Quote/SEB.pm
Labels: next release

#86 update parsing for changed layout on dwsfunds source page
  lib/Finance/Quote/DWS.pm
Labels: modified scraping, next release

#103 Changed source for BVB exchange
  lib/Finance/Quote/BSERO.pm
Labels: modified scraping, new source URL, next release

#105 Adding module for fondsweb.com (Germany)
  lib/Finance/Quote.pm
  lib/Finance/Quote/Fondsweb.pm
  t/fondsweb.t
Labels: new module, next release
