Repository finance-quote/finance-quote, pull requests merged in 2023-08, with the labels that each got.

#331 Fix for updated Bloomberg website
  Modules-README.yml
  lib/Finance/Quote/Bloomberg.pm
  t/bloomberg.t
Labels: modified scraping, next release

#332 Added back changes from eb4fd6e
  lib/Finance/Quote/AlphaVantage.pm
Labels: next release, enhancement

#336 Changes preparing for v1.58
  Changes
  htdocs/index.html
Labels: next release

#337 BSEIndia.pm - removed print for symbol not found
  Changes
  Modules-README.yml
  lib/Finance/Quote/BSEIndia.pm
  t/bseindia.t
Labels: module malfunction, next release, In Progress

#339 TSP.pm - Fix returns for when HTTP GET fails
  Changes
  Modules-README.yml
  lib/Finance/Quote/TSP.pm
Labels: module malfunction, next release, In Progress
