Repository finance-quote/finance-quote, pull requests merged in 2023-09, with the labels that each got.

#342 Skip rows in price table that don't have prices
  Changes
  Modules-README.yml
  lib/Finance/Quote/YahooWeb.pm
Labels: modified scraping, module malfunction, next release, In Progress

#340 New currencies in Stooq.pm
  Changes
  Modules-README.yml
  lib/Finance/Quote/Stooq.pm
Labels: next release, enhancement, In Progress

#345 Correct a self-reference in TMX.pm documentation
  Changes
  Modules-README.yml
  lib/Finance/Quote/TMX.pm
Labels: next release

#347 GoogleWeb.pm Update
  Changes
  Modules-README.yml
  lib/Finance/Quote/GoogleWeb.pm
Labels: modified scraping, next release, enhancement
