Repository finance-quote/finance-quote, pull requests merged in 2023-07, with the labels that each got.

#317 Minor documentation cleanup (Add install section to 'Documentation/RE…
  Documentation/README
  Documentation/Release.txt
  htdocs/discussion.html
Labels: next release, non-issue

#320 Fixes related to YahooJSON API URL - Issue #318
  Changes
  Modules-README.yml
  lib/Finance/Quote/CurrencyRates/YahooJSON.pm
  lib/Finance/Quote/YahooJSON.pm
Labels: modified scraping, next release

#321 Fixed YahooWeb for single character symbols
  Changes
  Modules-README.yml
  lib/Finance/Quote/YahooWeb.pm
  t/yahooweb.t
Labels: module malfunction, next release

#322 YahooWeb.pm Changes
  Changes
  Modules-README.yml
  dist.ini
  lib/Finance/Quote/YahooWeb.pm
Labels: new source URL, modified scraping, next release

#326 AlphaVantage - Currency scaling workaround
  Changes
  Modules-README.yml
  lib/Finance/Quote/AlphaVantage.pm
  t/alphavantage.t
Labels: next release, enhancement

#328 AlphaVantage.pm Fixed check for "Information" JSON
  Changes
  Modules-README.yml
  lib/Finance/Quote/AlphaVantage.pm
Labels: next release, enhancement
