Repository finance-quote/finance-quote, pull requests merged in 2023-12, with the labels that each got.

#352 Fix scraper in Finanzpartner.pm
  Changes
  Modules-README.yml
  lib/Finance/Quote/Finanzpartner.pm
  t/finanzpartner.t
Labels: modified scraping, module malfunction, next release

#356 Added BATS to GoogleWeb. Disabled Fidelity.pm
  Changes
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/GoogleWeb.pm
  t/googleweb.t
Labels: modified scraping, next release

#353 Fixed XETRA, Tradegate and SInvestor after webpage was restructured
  Changes
  Modules-README.yml
  lib/Finance/Quote/Sinvestor.pm
  lib/Finance/Quote/Tradegate.pm
  lib/Finance/Quote/XETRA.pm
  t/tradegate.t
  t/xetra.t
Labels: modified scraping, next release

#357 Housekeeping for v1.59 release
  Changes
  Modules-README.yml
  README.md
  dist.ini
  htdocs/index.html
  lib/Finance/Quote.pm
Labels: next release, non-issue
