Repository finance-quote/finance-quote, pull requests merged in 2023-05, with the labels that each got.

#260 Add get_features as FQ class method to advertise list of methods, modules, and module parameters
  Documentation/Hackers-Guide
  lib/Finance/Quote.pm
  lib/Finance/Quote/AlphaVantage.pm
  lib/Finance/Quote/CurrencyRates/AlphaVantage.pm
  lib/Finance/Quote/CurrencyRates/Fixer.pm
  lib/Finance/Quote/CurrencyRates/OpenExchange.pm
  lib/Finance/Quote/IEXCloud.pm
  t/fq-class-methods.t
Labels: next release, enhancement, non-issue

#277 Miscellaneous minor changes
  Changes
  Modules-README.yml
  dist.ini
  lib/Finance/Quote.pm
Labels: non-issue

#279 MStarUK renamed to MorningstarUK
  Changes
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/MorningstarUK.pm
  t/morningstarUK.t
Labels: next release, enhancement

#280 Fix for Issue 278
  Changes
  Modules-README.yml
  lib/Finance/Quote/Bourso.pm
  t/bourso.t
Labels: module malfunction, next release

#284 Fix for issue #282 "yahoo_json issue resurfaced"
  Changes
  Modules-README.yml
  lib/Finance/Quote/CurrencyRates/YahooJSON.pm
  lib/Finance/Quote/YahooJSON.pm
Labels: modified scraping, module malfunction, next release, currency

#285 New module - TwelveData.pm
  Changes
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/TwelveData.pm
  t/twelvedata.t
Labels: new module

#289 Fix for Fool.pm
  Changes
  Modules-README.yml
  dist.ini
  lib/Finance/Quote/Fool.pm
  t/fool.t
Labels: module malfunction, next release

#292 move use strict to be the first statement
  Changes
  Modules-README.yml
  lib/Finance/Quote/TreasuryDirect.pm
  lib/Finance/Quote/TwelveData.pm
Labels: next release
