Repository finance-quote/finance-quote, pull requests merged in 2023-06, with the labels that each got.

#294 Add GitHub Actions
  .github/workflows/ci.yml
Labels: next release, non-issue, Tips and Tricks

#299 AEX - Fix for Issue #298
  Changes
  Modules-README.yml
  lib/Finance/Quote/AEX.pm
Labels: modified scraping, next release

#301 Changed IndiaMutual.pm to use IO::String
  Changes
  Modules-README.yml
  lib/Finance/Quote/IndiaMutual.pm
  t/indiamutual.t
Labels: modified scraping, next release

#302 MarketWatch
  Changes
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/BVB.pm
  lib/Finance/Quote/MarketWatch.pm
  t/marketwatch.t
Labels: new module, next release

#303 GoogleWeb Module
  Changes
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/GoogleWeb.pm
  t/googleweb.t
Labels: new module, next release

#304 sinvestor pages enhanced by close, change, p_change
  Changes
  Modules-README.yml
  lib/Finance/Quote/Sinvestor.pm
  lib/Finance/Quote/Tradegate.pm
  lib/Finance/Quote/XETRA.pm
  t/sinvestor.t
  t/tradegate.t
  t/xetra.t
Labels: next release, enhancement

#307 Corrected setting exchange in YahooJSON
  Changes
  Modules-README.yml
  lib/Finance/Quote/YahooJSON.pm
Labels: module malfunction, next release

#310 Added count kludge to Quote.pm
  lib/Finance/Quote.pm
Labels: next release, enhancement

#308 add INST_ID as optional parameter to XETRA, Tradegate and Sinvestor
  Changes
  Modules-README.yml
  lib/Finance/Quote/Sinvestor.pm
  lib/Finance/Quote/Tradegate.pm
  lib/Finance/Quote/XETRA.pm
  t/sinvestor.t
  t/tradegate.t
  t/xetra.t
Labels: modified scraping, enhancement
