Repository finance-quote/finance-quote, pull requests merged in 2024-09, with the labels that each got.

#422 FinanceAPI.pm - New Module
  Changes
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/FinanceAPI.pm
  t/financeapi.t
Labels: new module, next release

#424 Fix TesouroDireto module
  Changes
  Modules-README.yml
  lib/Finance/Quote/TesouroDireto.pm
  t/tesouro_direto.t
Labels: new source URL, next release, In Progress

#428 Housekeeping for v1.63
  dist.ini
  htdocs/index.html
Labels: next release

#429 Allow API_KEYs from Environment Variables in Fixer.pm and OpenExchange.pm
  Changes
  Modules-README.yml
  lib/Finance/Quote/CurrencyRates/Fixer.pm
  lib/Finance/Quote/CurrencyRates/OpenExchange.pm
Labels: next release, enhancement, In Progress

#430 Updated Bourso.pm to address #417.
  Changes
  Modules-README.yml
  lib/Finance/Quote/Bourso.pm
Labels: next release, In Progress

#431 Added FinanceAPI Currency Rates Module
  Changes
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/CurrencyRates/FinanceAPI.pm
  t/currency.t
Labels: new module, next release, currency, In Progress

#432 Updated YahooJSON to validate dividend yield.
  Changes
  Modules-README.yml
  lib/Finance/Quote/YahooJSON.pm
Labels: module malfunction, next release, In Progress
