Repository finance-quote/finance-quote, pull requests merged in 2024-05, with the labels that each got.

#392 Restore Fool.pm
  Changes
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/Fool.pm
  t/fool.t
Labels: new module, modified scraping, next release

#393 MarketWatch Fix
  Changes
  Modules-README.yml
  dist.ini
  lib/Finance/Quote/MarketWatch.pm
Labels: module malfunction, next release

#394 YahooJSON.pm
  Changes
  Modules-README.yml
  dist.ini
  lib/Finance/Quote/YahooJSON.pm
Labels: next release, enhancement, In Progress

#395 Released CurrencyFreaks.pm module.
  Changes
  Modules-README.yml
  README.md
  lib/Finance/Quote.pm
  lib/Finance/Quote/Currencies.pm
  lib/Finance/Quote/CurrencyRates/CurrencyFreaks.pm
  t/currency.t
Labels: new module, next release, currency

#397 AlphaVantage - Remove Throttling
  Changes
  Modules-README.yml
  README.md
  lib/Finance/Quote/AlphaVantage.pm
  lib/Finance/Quote/YahooJSON.pm
  t/alphavantage.t
Labels: next release, enhancement, In Progress

#398 Fixed AEX
  Changes
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/AEX.pm
  lib/Finance/Quote/ASEGR.pm
  t/aex.t
  t/asegr.t
Labels: modified scraping, next release, In Progress

#400 Pre-Release Housekeeping v1.62
  htdocs/index.html
  lib/Finance/Quote.pm
Labels: next release

#402 NZX Fix
  Changes
  Modules-README.yml
  lib/Finance/Quote/NZX.pm
  t/nzx.t
Labels: modified scraping, next release

#403 Minor housekeeping for MorningstarUK and ASX
  Modules-README.yml
  t/aufunds.t
  t/morningstarAU.t
Labels: Documentation
