Repository finance-quote/finance-quote, pull requests merged in 2024-04, with the labels that each got.

#367 Contributing POD
  CONTRIBUTING.pod
Labels: next release, non-issue, Documentation

#374 Removed failing modules.
  Changes
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/Cdnfundlibrary.pm
  lib/Finance/Quote/Fidelity.pm
  lib/Finance/Quote/Fool.pm
  lib/Finance/Quote/Fundata.pm
  t/cdnfundlibrary.t
  t/fidelity.t
  t/fool.t
  t/fundata.t
Labels: next release

#381 Add additional URL fetch to YahooJSON.pm
  Changes
  Modules-README.yml
  htdocs/index.html
  lib/Finance/Quote/SIX.pm
  lib/Finance/Quote/YahooJSON.pm
Labels: next release, In Progress

#384 YahooWeb Fixes
  Changes
  Modules-README.yml
  dist.ini
  lib/Finance/Quote/YahooWeb.pm
Labels: modified scraping, next release, In Progress

#388 Minor change to TwelveData.pm - Add "last"
  Changes
  Modules-README.yml
  lib/Finance/Quote/TwelveData.pm
Labels: module malfunction, next release

#387 Updated yahooJSON.pm to handle EU consent in robust way.
  Changes
  Modules-README.yml
  dist.ini
  lib/Finance/Quote/YahooJSON.pm
  t/yahoojson.t
Labels: modified scraping, In Progress

#391 New Module - StockData.pm
  Changes
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/StockData.pm
  t/stockdata.t
Labels: new module, next release
