Repository finance-quote/finance-quote, pull requests merged in 2024-10, with the labels that each got.

#436 Rewrite of OnVista.pm
  Changes
  Modules-README.yml
  dist.ini
  lib/Finance/Quote.pm
  lib/Finance/Quote/OnVista.pm
  t/02-pod-coverage.t
  t/onvista.t
Labels: modified scraping, next release, In Progress

#437 Comdirect.pm Changes to Fix Issue #413
  Changes
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/Comdirect.pm
  t/comdirect.t
Labels: modified scraping, next release, In Progress

#440 Comdirect.pm
  Modules-README.yml
  lib/Finance/Quote/Comdirect.pm
  t/comdirect.t
Labels: modified scraping, next release, In Progress

#438 Update Modules-README.yml: formatting and comment on oslobors failure
  Modules-README.yml
Labels: Documentation

#439 Update CSE.pm - add more labels and update Modules-README.yml
  Changes
  Modules-README.yml
  lib/Finance/Quote/CSE.pm
  t/cse.t
Labels: modified scraping, next release, In Progress

#441 Minor Fix to FinanceAPI
  Documentation/Hackers-Guide
  Modules-README.yml
  lib/Finance/Quote.pm
  lib/Finance/Quote/AlphaVantage.pm
  lib/Finance/Quote/FinanceAPI.pm
  lib/Finance/Quote/IEXCloud.pm
  new-API-notes.txt
  t/iexcloud.t
Labels: next release, enhancement, In Progress

#446 Stooq.pm Fix
  Changes
  Modules-README.yml
  lib/Finance/Quote/Stooq.pm
Labels: module malfunction, next release, In Progress
