Repository finance-quote/finance-quote, pull requests merged in 2025-07, with the labels that each got.

#504 Currency freaks
  Changes
  Modules-README.yml
  lib/Finance/Quote/CurrencyRates/CurrencyFreaks.pm
Labels: next release, enhancement, currency, In Progress

#506 Release1.66
  dist.ini
  htdocs/index.html
Labels: next release, In Progress

#507 Using official Tesouro Direto URL (www.tesourodireto.com.br)
  Changes
  Modules-README.yml
  lib/Finance/Quote/TesouroDireto.pm
Labels: enhancement, In Progress

#508 Contributing document
  CONTRIBUTING.md
  CONTRIBUTING.pod
  dist.ini
Labels: next release, non-issue, In Progress, Documentation

#511 Methodinfo
  Changes
  Modules-README.yml
  lib/Finance/Quote/BorsaItaliana.pm
  lib/Finance/Quote/MarketWatch.pm
  t/borsa_italiana.t
Labels: enhancement, In Progress
