Repository finance-quote/finance-quote, pull requests merged in 2025-08, with the labels that each got.

#517 Fix MorningstarCH.pm - basically copying MorningstarUK.pm.
  Changes
  Modules-README.yml
  lib/Finance/Quote/MorningstarCH.pm
  t/morningstarCH.t
Labels: new source URL, modified scraping, next release, In Progress

#518 Modified dist.ini for issue #514
  dist.ini
  lib/Finance/Quote.pm
Labels: next release, non-issue

#519 Add methodinfo
  Modules-README.yml
  lib/Finance/Quote/BSEIndia.pm
  lib/Finance/Quote/BVB.pm
  lib/Finance/Quote/Deka.pm
  lib/Finance/Quote/Finanzpartner.pm
  lib/Finance/Quote/Fondsweb.pm
Labels: enhancement, In Progress

#520 Changes to address TEST_AUTHOR failures.
  CONTRIBUTING.md
  Documentation/Hackers-Guide
  dist.ini
  lib/Finance/Quote.pm
  lib/Finance/Quote/FTfunds.pm
  lib/Finance/Quote/OnVista.pm
Labels: next release, In Progress

#521 Correct syntax errors in SwissFundData.pm
  lib/Finance/Quote/SwissFundData.pm
Labels: In Progress
